<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="GreenDonut.Data.EntityFramework" />
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.AspNetCore.CommandLine" />
    <PackageReference Include="HotChocolate.Types.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ragkivio.Application\Ragkivio.Application.csproj" />
    <ProjectReference Include="..\Ragkivio.Infrastructure\Ragkivio.Infrastructure.csproj" />
    <ProjectReference Include="..\Ragkivio.Persistence\Ragkivio.Persistence.csproj" />
  </ItemGroup>

</Project>
