<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="HotChocolate.AspNetCore" Version="16.6.2" />
    <PackageVersion Include="HotChocolate.AspNetCore.CommandLine" Version="16.6.2" />
	<PackageVersion Include="HotChocolate.Types.Analyzers" Version="16.6.2"/>
  </ItemGroup>
</Project>
